esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${area}

logger:
  level: ${log_level}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home
  fast_connect: true
  reboot_timeout: 0s # Default 15min, Won't reboot when HA is down.
  ap:
    ssid: ${name}_AP
    password: !secret esphome_ap_password
    ap_timeout: 3min

ota:
  - platform: esphome
    password: !secret esphome_ota_password

# web_server:
#   port: 80
#   # https://esphome.io/components/web_server.html

# api:
#   encryption:
#     key: !secret api_encryption_key

captive_portal:

text_sensor:
  - platform: version
    name: "esphome_version"
    id: ${name}_esphome_version
    hide_timestamp: True
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      id: ${name}_ip_address
      name: "ip_address"
      icon: "mdi:ip-outline"
      update_interval: "${diagnostic_interval}"
      entity_category: diagnostic
      disabled_by_default: false
    ssid:
      id: ${name}_ssid
      name: "ssid"
      icon: "mdi:wifi-settings"
      update_interval: "${diagnostic_interval}"
      entity_category: diagnostic
      disabled_by_default: false
    bssid:
      id: ${name}_bssid
      name: "bssid"
      icon: "mdi:wifi-settings"
      update_interval: "${diagnostic_interval}"
      entity_category: diagnostic
      disabled_by_default: false
    mac_address:
      id: ${name}_mac_address
      name: "mac_address"
      icon: "mdi:network-outline"
      entity_category: diagnostic
      disabled_by_default: false

sensor:
  # WiFi Signal Strength
  - platform: wifi_signal
    name: "wifi_signal"
    id: ${name}_wifi_signal
    update_interval: "${diagnostic_interval}"
    disabled_by_default: false
    entity_category: diagnostic

  - platform: uptime
    name: "uptime"
    id: ${name}_uptime
    update_interval: "${heartbeat_interval}"
    disabled_by_default: true
    entity_category: diagnostic
